<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10"/>
    </ItemGroup>

    <ItemGroup>
        <Content Update="wwwroot/**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ProtonTune.Core\ProtonTune.Core.csproj" />
      <ProjectReference Include="..\ProtonTune.Services\ProtonTune.Services.csproj" />
    </ItemGroup>

</Project>
